CREATE TABLE ACCOUNT (
	mailadress VARCHAR(256) PRIMARY KEY,
	password VARCHAR(256)  NOT NULL UNIQUE,
	solt VARCHAR(256)  NOT NULL UNIQUE,
	nick_name VARCHAR(256)  NOT NULL UNIQUE,
	real_name VARCHAR(256)  NOT NULL UNIQUE,
	birthday DATE(16)  NOT NULL,
	school_name VARCHAR(256)  NOT NULL,
	file_name VARCHAR(32) NOT NULL UNIQUE
);